package io.github.sunshinewzy.sunstcore.enums

import org.bukkit.Material
import org.bukkit.Material.*

enum class SMaterial(val types: List<Material>) {
    FENCE(OAK_FENCE, ACACIA_FENCE, BIRCH_FENCE, CRIMSON_FENCE, DARK_OAK_FENCE, JUNGLE_FENCE, NETHER_BRICK_FENCE, SPRUCE_FENCE, WARPED_FENCE),
    FENCE_WOOD(OAK_FENCE, ACACIA_FENCE, BIRCH_FENCE, CRIMSON_FENCE, DARK_OAK_FENCE, JUNGLE_FENCE, SPRUCE_FENCE),
    
    WOOD(OAK_WOOD, JUNGLE_WOOD, ACACIA_WOOD, BIRCH_WOOD, DARK_OAK_WOOD, SPRUCE_WOOD),
    
    WOOL(BLACK_WOOL, BLUE_WOOL, BROWN_WOOL, CYAN_WOOL, GRAY_WOOL, GREEN_WOOL, LIGHT_BLUE_WOOL, LIGHT_GRAY_WOOL, LIME_WOOL, MAGENTA_WOOL, ORANGE_WOOL, PINK_WOOL, PURPLE_WOOL, RED_WOOL, WHITE_WOOL, YELLOW_WOOL),
    
    LEAVES(ACACIA_LEAVES, BIRCH_LEAVES, DARK_OAK_LEAVES, JUNGLE_LEAVES, OAK_LEAVES, SPRUCE_LEAVES)
    
    ;
    
    
    constructor(vararg types: Material) : this(types.toList())


}